### PR TITLE
Rename MyShareEx to HeutagogyShare and HeutagogyMobileApp to Heutagogy.

### PR DESCRIPTION
**Pull request by drets**

### CODE REVIEW

**Comment by rasendubi** [comment]
Why `HeutagogyShare` and not `Heutagogy`?

**Comment by drets** [comment]
How would you distinguish the components then?

Heutagogy is reserved for main app.

**Comment by rasendubi** [comment]
How does Skype do?

**Comment by rasendubi** [comment]
I'm not talking about component name, but title in the "Share via" dialog.

**Comment by drets** [comment]
Dunno. But definitely they don't write on `react-native` using `react-native-share-extension`. If you know how to  do it, please do!

**Comment by drets** [comment]
I will try to do a few tweaks to make it "Heutagogy"...

**Comment by drets** [comment]
@rasendubi thanks! It's actually quite easy: https://github.com/heutagogy/HeutagogyMobileApp/pull/4 :smile:

**Pull request merged**
