### PR TITLE
Remade pages with material design

### PR DESCRIPTION
**Pull request by rasendubi**
Before:
2017-03-09-014759_498x878_scrot

2017-03-09-030245_498x878_scrot

After:
2017-03-09-013159_498x878_scrot

2017-03-09-025947_498x878_scrot

### CODE REVIEW

**Comment by drets** [comment]
IMO Previous version of login screen UI is more UX friendly than this one.

In order to make it better I'd try to:
• increase font and/or make more spaces between controls
• use fixed floating label instead of regular floating label:

selection_114

(as you can see from the image when there is cursor and value is not set − cursor is overlapped with label makes UI look worse)

**Comment by rasendubi** [comment]
That's strange because textinput library demo (gif) does not show the issue: https://github.com/evblurbs/react-native-md-textinput

**Comment by drets** [comment]
(checked on real device − the same issue)

**Comment by rasendubi** [comment]
We might also try text fields from [react-native-material-kit](https://github.com/xinthink/react-native-material-kit#text-fields).

**Pull request merged**
